server:
  port: 1337

database:
  path: "./data/hashcat.db"

upload:
  directory: "./uploads"
  # New: Enhanced upload configuration for large files
  max_file_size: "10GB"
  chunk_size: "10MB"
  timeout: "30m"
  retry_attempts: 3
  retry_delay: "2s" 
